import type { ImageRef, SiteContent } from "./types";
import seedImages from "./seed-images.json";

/** Look up a processed owner photo (dimensions + blur placeholder included). */
function photo(key: keyof typeof seedImages, alt: string): ImageRef {
  const img = seedImages[key];
  return { ...img, alt };
}

/**
 * Initial site content built from the owner's real work photos. It is shown
 * until the owner saves their first change from the admin panel, after which
 * a copy of this content becomes the editable document.
 */
export const seedContent: SiteContent = {
  updatedAt: "2026-07-21T00:00:00.000Z",
  settings: {
    businessName: "پویا چوب",
    ownerName: "پویا",
    tagline: "کارگاه نجاری و ساخت سفارشی",
    heroTitle: "کابینت و مصنوعات چوبی، دقیقاً برای فضای شما",
    heroSubtitle:
      "طراحی و ساخت کابینت آشپزخانه، کمد دیواری و مصنوعات چوبی و ام‌دی‌اف؛ با اندازه‌گیری دقیق، متریال درست و نصب تمیز.",
    aboutIntro:
      "من پویا هستم؛ نجار. هر پروژه را از شناخت فضا و نیاز واقعی شما شروع می‌کنم و تا نصب نهایی، خودم کنار کار می‌مانم.",
    aboutBody:
      "در کارگاه من طراحی از روی کاتالوگ کپی نمی‌شود. ابعاد فضا، عادت‌های استفاده، نور و بودجه کنار هم قرار می‌گیرند تا چیزی ساخته شود که سال‌ها درست کار کند.\n\nاز انتخاب ورق و یراق تا برش، مونتاژ و نصب، همه مراحل زیر نظر خودم انجام می‌شود. نتیجه باید هم زیبا باشد، هم در استفاده روزمره دقیق و قابل اعتماد بماند.\n\nاگر برای آشپزخانه، اتاق خواب یا فضای کارتان به دنبال کاری تمیز و حساب‌شده هستید، عکس‌های نمونه‌کارها را ببینید و برای مشاوره تماس بگیرید.",
    portrait: photo("portrait-pooya", "پویا در کارگاه نجاری، کنار درِ کابینت گردویی"),
    heroImage: photo("kitchen-cream-walnut", "کابینت آشپزخانه کرم و گردو با نور مخفی"),
    phone: "09123456789",
    whatsapp: "09123456789",
    instagram: "pooyachoob",
    address: "تهران — بازدید از کارگاه با هماهنگی قبلی",
    serviceArea: "تهران و حومه",
    hours: "شنبه تا پنج‌شنبه، ۹ تا ۱۸",
    experienceYears: "15",
  },
  categories: [
    {
      id: "cat_kitchen",
      title: "کابینت آشپزخانه",
      slug: "کابینت-آشپزخانه",
      description: "کابینت مدرن، نئوکلاسیک و ممبران؛ متناسب با ابعاد و نور آشپزخانه شما.",
      cover: photo("kitchen-modern-island", "کابینت آشپزخانه مدرن با جزیره چوبی"),
      order: 1,
    },
    {
      id: "cat_wardrobe",
      title: "کمد دیواری",
      slug: "کمد-دیواری",
      description: "کمد دیواری، اتاق لباس و میز آرایش؛ با چیدمان داخلی حساب‌شده.",
      cover: photo("wardrobe-sliding-walnut", "کمد ریلی گردویی با چیدمان داخلی"),
      order: 2,
    },
    {
      id: "cat_coffeebar",
      title: "کافی‌بار خانگی",
      slug: "کافی-بار-خانگی",
      description: "گوشه قهوه و بار خانگی؛ از کنج دنج تا ویترین نئوکلاسیک.",
      cover: photo("coffee-bar-neo-niche", "کافی‌بار نئوکلاسیک با طاق چوبی"),
      order: 3,
    },
    {
      id: "cat_nightstand",
      title: "پاتختی و دراور",
      slug: "پاتختی-و-دراور",
      description: "پاتختی، دراور و مبلمان کوچک اتاق خواب.",
      cover: photo("nightstand-oak", "پاتختی چوبی دوکشو"),
      order: 4,
    },
  ],
  projects: [
    {
      id: "prj_kitchen_island",
      title: "آشپزخانه مدرن با جزیره چوبی",
      slug: "آشپزخانه-مدرن-با-جزیره-چوبی",
      categoryId: "cat_kitchen",
      summary: "کابینت بدون دستگیره با جزیره صفحه‌چوبی و ویترین نوردار کنار ورودی.",
      description:
        "بدنه اصلی با رنگ روشن آرام نگه داشته شد تا جزیره با صفحه چوبی، نقطه تمرکز فضا باشد. بین کابینت و سقف نور مخفی اجرا شده و ویترین شیشه‌ای کنار ورودی، جای نمایش ظروف را بدون شلوغی فراهم می‌کند.",
      materials: ["ام‌دی‌اف مات", "صفحه چوبی"],
      featured: true,
      order: 1,
      createdAt: "2026-06-01T00:00:00.000Z",
      images: [
        photo("kitchen-modern-island", "نمای کلی آشپزخانه مدرن با جزیره چوبی"),
      ],
    },
    {
      id: "prj_kitchen_oak_frame",
      title: "آشپزخانه سفید با قاب بلوط",
      slug: "آشپزخانه-سفید-با-قاب-بلوط",
      categoryId: "cat_kitchen",
      summary: "هایگلاس سفید در قاب چوب بلوط، با میز بار یکپارچه.",
      description:
        "قاب و ستون‌های بلوطی، کابینت سفید هایگلاس را مثل یک قطعه مبلمان در قلب خانه نشانده‌اند. میز بار با همان چوب اجرا شده تا آشپزخانه و نشیمن به هم گره بخورند.",
      materials: ["هایگلاس سفید", "روکش بلوط"],
      featured: false,
      order: 2,
      createdAt: "2026-05-20T00:00:00.000Z",
      images: [photo("kitchen-white-oak-frame", "آشپزخانه سفید هایگلاس با قاب بلوط و میز بار")],
    },
    {
      id: "prj_kitchen_bench",
      title: "آشپزخانه روشن با نشیمن کنار پنجره",
      slug: "آشپزخانه-روشن-با-نشیمن-کنار-پنجره",
      categoryId: "cat_kitchen",
      summary: "کابینت سفید با خط چوبی و نیمکت نشیمن زیر پنجره.",
      description:
        "زیر پنجره به جای کابینت معمولی، یک نیمکت نشیمن با کشو اجرا شد تا نور و منظره حفظ شود. خط چوبی باریک در پاخور و لبه‌ها، فضای یکدست سفید را گرم‌تر کرده است.",
      materials: ["ام‌دی‌اف سفید", "نوار چوبی"],
      featured: false,
      order: 3,
      createdAt: "2026-05-10T00:00:00.000Z",
      images: [photo("kitchen-window-bench", "آشپزخانه سفید با نیمکت کنار پنجره")],
    },
    {
      id: "prj_kitchen_cream_walnut",
      title: "آشپزخانه کرم و گردو",
      slug: "آشپزخانه-کرم-و-گردو",
      categoryId: "cat_kitchen",
      summary: "ترکیب گرم کرم و گردو با نور مخفی بالای کابینت.",
      description:
        "درهای کرم براق با بدنه گردویی قاب شده‌اند و نور خطی بالای کابینت، ارتفاع فضا را بیشتر نشان می‌دهد. میز غذاخوری با همان زبان طراحی کنار آشپزخانه نشسته است.",
      materials: ["ام‌دی‌اف کرم", "روکش گردو"],
      featured: false,
      order: 4,
      createdAt: "2026-04-25T00:00:00.000Z",
      images: [photo("kitchen-cream-walnut", "آشپزخانه کرم و گردو با نور مخفی")],
    },
    {
      id: "prj_kitchen_gray",
      title: "آشپزخانه سفید و طوسی",
      slug: "آشپزخانه-سفید-و-طوسی",
      categoryId: "cat_kitchen",
      summary: "ترکیب دو رنگ در یک آشپزخانه؛ سفید بالا، طوسی میانه و ستون دکوراتیو.",
      description:
        "کابینت‌های بالایی سفید و ردیف میانی طوسی، ارتفاع را تقسیم کرده‌اند تا فضا سنگین نشود. ستون انتهایی با قفسه‌های باز، جای نمایش و دسترسی سریع را ساخته است.",
      materials: ["هایگلاس سفید", "هایگلاس طوسی"],
      featured: false,
      order: 5,
      createdAt: "2026-04-10T00:00:00.000Z",
      images: [photo("kitchen-white-gray", "آشپزخانه هایگلاس سفید و طوسی")],
    },
    {
      id: "prj_kitchen_shaker",
      title: "آشپزخانه کرم با صفحه چوبی",
      slug: "آشپزخانه-کرم-با-صفحه-چوبی",
      categoryId: "cat_kitchen",
      summary: "درهای قاب‌دار کرم، صفحه و دیوارپوش چوبی، یراق مشکی.",
      description:
        "درهای قاب‌دار ساده با یراق مشکی، حال‌وهوای کلاسیک ملایمی به فضا داده‌اند. صفحه کار و دیوارپوش چوبی، گرمای چوب را به کل آشپزخانه می‌رساند.",
      materials: ["ام‌دی‌اف قاب‌دار", "صفحه چوبی"],
      featured: false,
      order: 6,
      createdAt: "2026-03-20T00:00:00.000Z",
      images: [photo("kitchen-shaker-wood", "آشپزخانه کرم قاب‌دار با صفحه چوبی")],
    },
    {
      id: "prj_kitchen_ushape",
      title: "آشپزخانه یوشکل سفید و چوب",
      slug: "آشپزخانه-یوشکل-سفید-و-چوب",
      categoryId: "cat_kitchen",
      summary: "چیدمان یوشکل با ستون‌های چوبی و جای لوازم توکار.",
      description:
        "چیدمان یوشکل، مسیر کار را کوتاه نگه می‌دارد؛ یخچال و فر داخل ستون‌های چوبی توکار شده‌اند و ترکیب سفید و چوب، فضا را روشن و گرم نگه داشته است.",
      materials: ["ام‌دی‌اف سفید", "روکش چوب"],
      featured: false,
      order: 7,
      createdAt: "2026-03-05T00:00:00.000Z",
      images: [photo("kitchen-u-shape", "آشپزخانه یوشکل سفید و چوب با لوازم توکار")],
    },
    {
      id: "prj_drawer_organizer",
      title: "نظم‌دهنده چوبی داخل کشو",
      slug: "نظم-دهنده-چوبی-داخل-کشو",
      categoryId: "cat_kitchen",
      summary: "جداکننده قاشق و چنگال، ساخته‌شده دقیق به اندازه هر کشو.",
      description:
        "نظم‌دهنده‌ها از چوب بلوط و گردو، دقیقاً به ابعاد داخلی کشو ساخته می‌شوند؛ نه لق می‌زنند و نه جای هدررفته باقی می‌گذارند. جزئیاتی که هر روز موقع استفاده به چشم می‌آید.",
      materials: ["چوب بلوط", "چوب گردو"],
      featured: false,
      order: 8,
      createdAt: "2026-02-15T00:00:00.000Z",
      images: [
        photo("drawer-organizer-walnut", "نظم‌دهنده گردویی قاشق و چنگال داخل کشو"),
        photo("drawer-organizer-oak", "نظم‌دهنده بلوطی داخل کشو"),
      ],
    },

    {
      id: "prj_wardrobe_vanity_led",
      title: "کمد دیواری با میز آرایش نوردار",
      slug: "کمد-دیواری-با-میز-آرایش-نوردار",
      categoryId: "cat_wardrobe",
      summary: "کمد سرتاسری با آینه نوردار و میز آرایش یکپارچه.",
      description:
        "میز آرایش با آینه نوردار، وسط کمد سرتاسری نشسته تا اتاق به فضای جداگانه‌ای نیاز نداشته باشد. کشوهای زیر میز، لوازم روزمره را جمع می‌کنند و بدنه چوبی، کل دیوار را یکپارچه می‌کند.",
      materials: ["ام‌دی‌اف کرم", "روکش چوب"],
      featured: true,
      order: 9,
      createdAt: "2026-06-05T00:00:00.000Z",
      images: [photo("wardrobe-vanity-led", "کمد دیواری با میز آرایش و آینه نوردار")],
    },
    {
      id: "prj_wardrobe_vanity_white",
      title: "کمد سفید با کنج آرایش",
      slug: "کمد-سفید-با-کنج-آرایش",
      categoryId: "cat_wardrobe",
      summary: "کمد دودرب بلند با کنج آینه و دراور برای اتاق خواب.",
      description:
        "درهای ساده سفید با قاب چوبی، حجم کمد را سبک نشان می‌دهند. کنج آینه با دراور دوکشو، بدون اشغال فضای اضافه، جای آماده‌شدن صبح‌ها را فراهم کرده است.",
      materials: ["ام‌دی‌اف سفید", "قاب چوبی"],
      featured: false,
      order: 10,
      createdAt: "2026-05-25T00:00:00.000Z",
      images: [photo("wardrobe-vanity-white", "کمد سفید با کنج آینه و دراور")],
    },
    {
      id: "prj_wardrobe_gloss",
      title: "کمد هایگلاس با آینه",
      slug: "کمد-هایگلاس-با-آینه",
      categoryId: "cat_wardrobe",
      summary: "کمد سفید براق با درِ آینه‌دار و کشوهای بیرونی.",
      description:
        "سطح براق درها نور را برمی‌گرداند و اتاق را بزرگ‌تر نشان می‌دهد. آینه قدی داخل قاب کمد اجرا شده و سه کشوی بیرونی، دسترسی سریع بدون باز کردن درها را فراهم می‌کنند.",
      materials: ["هایگلاس سفید"],
      featured: false,
      order: 11,
      createdAt: "2026-05-15T00:00:00.000Z",
      images: [photo("wardrobe-mirror-gloss", "کمد هایگلاس سفید با آینه و کشو")],
    },
    {
      id: "prj_wardrobe_classic",
      title: "کمد چهاردرب کلاسیک",
      slug: "کمد-چهاردرب-کلاسیک",
      categoryId: "cat_wardrobe",
      summary: "کمد مستقل چهاردرب با بدنه و دستگیره چوبی.",
      description:
        "برای اتاقی که کمد توکار ندارد، یک کمد مستقل با بدنه چوبی و درهای کرم ساخته شد؛ دستگیره‌های چوبی بلند، دسترسی را راحت می‌کنند و ظاهری آرام دارند.",
      materials: ["ام‌دی‌اف کرم", "چوب راش"],
      featured: false,
      order: 12,
      createdAt: "2026-04-28T00:00:00.000Z",
      images: [photo("wardrobe-classic-cream", "کمد چهاردرب کرم با قاب چوبی")],
    },
    {
      id: "prj_wardrobe_display",
      title: "کمد گردویی با ویترین",
      slug: "کمد-گردویی-با-ویترین",
      categoryId: "cat_wardrobe",
      summary: "کمد ریلی گردو با ستون ویترین شیشه‌ای و کشوهای داخلی.",
      description:
        "ستون ویترین با در شیشه‌ای دودی، جای کیف و وسایل خاص است و بقیه کمد پشت درهای ریلی پنهان می‌شود. چیدمان داخلی با رگال، قفسه و کشو بر اساس وسایل واقعی طراحی شده است.",
      materials: ["روکش گردو", "شیشه دودی"],
      featured: true,
      order: 13,
      createdAt: "2026-04-15T00:00:00.000Z",
      images: [photo("wardrobe-walnut-display", "کمد گردویی با ویترین شیشه‌ای و درهای ریلی")],
    },
    {
      id: "prj_wardrobe_sliding",
      title: "کمد ریلی گردو و کرم",
      slug: "کمد-ریلی-گردو-و-کرم",
      categoryId: "cat_wardrobe",
      summary: "درهای ریلی دو رنگ برای اتاقی که جای باز شدن در ندارد.",
      description:
        "در فضای کم‌عمق، درهای ریلی بهترین جواب‌اند. ترکیب گردو و کرم مات، حجم بزرگ کمد را سبک کرده و ریل‌های آرام‌بند، حرکت درها را بی‌صدا نگه می‌دارند.",
      materials: ["روکش گردو", "ام‌دی‌اف مات"],
      featured: false,
      order: 14,
      createdAt: "2026-03-25T00:00:00.000Z",
      images: [photo("wardrobe-sliding-walnut", "کمد ریلی دو رنگ گردو و کرم")],
    },
    {
      id: "prj_wardrobe_open",
      title: "کمد باز با چیدمان داخلی",
      slug: "کمد-باز-با-چیدمان-داخلی",
      categoryId: "cat_wardrobe",
      summary: "ترکیب بخش باز و بسته؛ رگال، قفسه و کشو در دسترس.",
      description:
        "بخش‌های باز برای لباس‌های روزمره و بخش بسته برای بقیه وسایل. کشوها و قفسه‌ها طوری تقسیم شده‌اند که همه‌چیز دیده شود و مرتب بماند.",
      materials: ["ام‌دی‌اف روکش‌دار"],
      featured: false,
      order: 15,
      createdAt: "2026-03-10T00:00:00.000Z",
      images: [photo("wardrobe-open-oak", "کمد باز با رگال و کشو")],
    },
    {
      id: "prj_closet",
      title: "اتاق لباس با قفسه‌بندی کامل",
      slug: "اتاق-لباس-با-قفسه-بندی-کامل",
      categoryId: "cat_wardrobe",
      summary: "دیوار تا دیوار؛ رگال، جاکفشی، قفسه کیف و کشو.",
      description:
        "هر وسیله جای مشخص خودش را دارد: رگال بلند و کوتاه، قفسه‌های کیف و کلاه، جاکفشی شیب‌دار و کشوهای عمیق. قبل از ساخت، فهرست وسایل با کارفرما نهایی شد تا هیچ فضایی هدر نرود.",
      materials: ["ام‌دی‌اف روکش‌دار", "یراق کشویی"],
      featured: false,
      order: 16,
      createdAt: "2026-02-25T00:00:00.000Z",
      images: [photo("closet-organizer", "اتاق لباس با قفسه‌بندی کامل")],
    },
    {
      id: "prj_wardrobe_minimal",
      title: "کمد سرتاسری مینیمال",
      slug: "کمد-سرتاسری-مینیمال",
      categoryId: "cat_wardrobe",
      summary: "از کف تا سقف، بدون دستگیره اضافه؛ فقط دو خط چوبی.",
      description:
        "درها تا سقف ادامه دارند تا دیوار کاملاً یکدست شود و بالای کمد جای خاک‌خور نماند. دستگیره‌های چوبی باریک، تنها جزئیات نمای کار هستند.",
      materials: ["ام‌دی‌اف مات", "دستگیره چوبی"],
      featured: false,
      order: 17,
      createdAt: "2026-02-10T00:00:00.000Z",
      images: [photo("wardrobe-minimal-cream", "کمد سرتاسری مینیمال کرم")],
    },

    {
      id: "prj_coffee_neo_cream",
      title: "کافی‌بار نئوکلاسیک کرم",
      slug: "کافی-بار-نئوکلاسیک-کرم",
      categoryId: "cat_coffeebar",
      summary: "طاق چوبی نوردار میان ویترین‌های شیشه‌ای، در قلب آشپزخانه نئوکلاسیک.",
      description:
        "کنج قهوه داخل یک طاق چوبی با نور مخفی نشسته و دو ستون ویترین با شیشه دودی، جای جام و بطری را ساخته‌اند. ترکیب کرم و چوب، این کنج را به نقطه اصلی فضا تبدیل کرده است.",
      materials: ["ام‌دی‌اف ممبران", "روکش بلوط", "شیشه دودی"],
      featured: true,
      order: 18,
      createdAt: "2026-06-10T00:00:00.000Z",
      images: [
        photo("coffee-bar-neo-niche", "کافی‌بار نئوکلاسیک با طاق چوبی نوردار"),
        photo("coffee-bar-neo-cream", "ویترین‌های شیشه‌ای دو طرف کافی‌بار"),
      ],
    },
    {
      id: "prj_coffee_neo_black",
      title: "کافی‌بار نئوکلاسیک مشکی",
      slug: "کافی-بار-نئوکلاسیک-مشکی",
      categoryId: "cat_coffeebar",
      summary: "ستون بار مشکی با طاق فلوتد، قفسه نوردار و کشوهای براق.",
      description:
        "بدنه مشکی با درهای فلوتد و یراق طلایی، کنار آشپزخانه سفید یک نقطه تمرکز چشمگیر ساخته است. قفسه‌های نوردار، لوازم قهوه و چای را قاب می‌گیرند.",
      materials: ["ام‌دی‌اف ممبران مشکی", "یراق طلایی"],
      featured: false,
      order: 19,
      createdAt: "2026-05-05T00:00:00.000Z",
      images: [photo("coffee-bar-neo-black", "کافی‌بار مشکی با طاق فلوتد و قفسه نوردار")],
    },
    {
      id: "prj_coffee_nook",
      title: "گوشه قهوه دنج",
      slug: "گوشه-قهوه-دنج",
      categoryId: "cat_coffeebar",
      summary: "کابینت کوچک با در حصیری و شلف‌های چوبی؛ جمع‌وجور و گرم.",
      description:
        "برای کنج‌های کوچک خانه: یک کابینت با در حصیری و صفحه روشن، دو شلف چوبی و جای آویز فنجان. همه لوازم قهوه در یک قدمی شما، بدون شلوغ کردن آشپزخانه.",
      materials: ["چوب راش", "حصیر طبیعی"],
      featured: false,
      order: 20,
      createdAt: "2026-04-05T00:00:00.000Z",
      images: [
        photo("coffee-nook-cane", "کابینت قهوه با در حصیری و شلف چوبی"),
        photo("coffee-bar-shelf", "شلف سفید با جای آویز فنجان"),
      ],
    },

    {
      id: "prj_nightstand_oak",
      title: "پاتختی چوبی دوکشو",
      slug: "پاتختی-چوبی-دوکشو",
      categoryId: "cat_nightstand",
      summary: "پاتختی بلوط با پایه‌های گرد و دستگیره مخفی.",
      description:
        "بدنه تمام‌روکش بلوط با دستگیره‌های داخل‌کار؛ ساده، سبک و بی‌ادعا. کشوها روی ریل آرام‌بند حرکت می‌کنند.",
      materials: ["روکش بلوط"],
      featured: true,
      order: 21,
      createdAt: "2026-06-15T00:00:00.000Z",
      images: [photo("nightstand-oak", "پاتختی بلوطی دوکشو با پایه گرد")],
    },
    {
      id: "prj_nightstand_white_wood",
      title: "پاتختی سفید و چوب",
      slug: "پاتختی-سفید-و-چوب",
      categoryId: "cat_nightstand",
      summary: "سه‌کشو با قاب چوبی و درهای سفید مات.",
      description:
        "قاب چوبی دور بدنه، خط گرمی دور حجم سفید کشیده است. سه کشوی هم‌اندازه، جای لوازم کنار تخت را کامل می‌کنند.",
      materials: ["ام‌دی‌اف سفید", "قاب چوبی"],
      featured: false,
      order: 22,
      createdAt: "2026-05-30T00:00:00.000Z",
      images: [photo("nightstand-white-wood", "پاتختی سه‌کشو سفید با قاب چوبی")],
    },
    {
      id: "prj_nightstand_gray",
      title: "پاتختی طوسی پایه‌فلزی",
      slug: "پاتختی-طوسی-پایه-فلزی",
      categoryId: "cat_nightstand",
      summary: "دوکشو با روکش بافت‌دار طوسی و پایه‌های فلزی مورب.",
      description:
        "روکش بافت‌دار، اثر انگشت و خط‌وخش را پنهان می‌کند و پایه‌های فلزی مورب، حال‌وهوای میدسنچری به اتاق می‌دهند.",
      materials: ["روکش بافت‌دار", "پایه فلزی"],
      featured: false,
      order: 23,
      createdAt: "2026-05-01T00:00:00.000Z",
      images: [photo("nightstand-gray", "پاتختی طوسی با پایه فلزی مشکی")],
    },
    {
      id: "prj_nightstand_white",
      title: "پاتختی سفید دوکشو",
      slug: "پاتختی-سفید-دوکشو",
      categoryId: "cat_nightstand",
      summary: "بافت پارچه‌ای ملایم با دستگیره و پایه مشکی.",
      description:
        "ورق با بافت پارچه‌ای ظریف، سطحی مات و خوش‌لمس ساخته است. دستگیره و پایه‌های مشکی، حجم سفید را قاب می‌گیرند. نمونه‌ای از کارهای نصب‌شده در منزل کارفرما.",
      materials: ["ام‌دی‌اف بافت‌دار", "یراق مشکی"],
      featured: false,
      order: 24,
      createdAt: "2026-04-20T00:00:00.000Z",
      images: [photo("nightstand-white", "پاتختی سفید دوکشو با پایه مشکی")],
    },
  ],
};
